blink_detector: 
  _target_: utils.detector.BufferedModule
  module:
    _target_: utils.detector.VerticalDistanceBlinkDetector
    eye_detector: 
      _target_: utils.detector.FaceMeshLandmarksDetector
      mask_size: 16
      default_landmarks_path: ./assets/default_landmarks.pkl
    calibrator:
      _target_: utils.detector.PeriodicCalibrator
      every_nth_frame: 1000
      buffer_size: 100
      quantile: 0.98
  buffer_size: 3
verbose: false
icon_path: ./assets/icon.png

defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .
